### ISSUE TITLE
Not working on neovim, MacVim, or vim with Spacevim on macOS.

### ISSUE THREAD

**Issue by raguay** [dustinknopoff/TeaCode-Vim-Extension#10]
When it executes, I get:
```
Error detected while processing function TeaCodeExpand:
line   16:
E117: Unknown function: js_decode
E15: Invalid expression: js_decode( ob )
line   17:
E121: Undefined variable: object
E15: Invalid expression: object.text
line   20:
E121: Undefined variable: object
E15: Invalid expression: object ==? 'null'
line   25:
E121: Undefined variable: s:result
E15: Invalid expression: "normal! i". s:result
line   41:
E117: Unknown function: provider#python#Call
line   44:
E121: Undefined variable: l
E15: Invalid expression: line + l + 1 " add offset
line   45:
E121: Undefined variable: c
E15: Invalid expression: cursor[2] + c - 1
```

Is it suppose to work on neovim? It is doing the same with normal Vim and SpaceVim. I guess it's an interaction with SpaceVim?

**Comment by didair** [comment]
Hi. You get this issue when the expander couldn't be found or when expand.sh can't be runned. If you look in your dotfile directory, can you find a file named expand.sh?

**Comment by didair** [comment]
Related to #6 (to-do item)

**Comment by raguay** [comment]
Looking into this directory: cd .cache/vimfiles/repos/github.com/dustinknopoff/TeaCode-Vim-Extension

This has every file in your repo, including the expand.sh file. Therefore, it should be able to run it unless it need the execute file permission set first.

**Comment by raguay** [comment]
I believe your script is assuming it is ran from the repo directly. But, I bet SpaceVim is running it from the `.SpaceVim` directory (which is linked to the `.vim` directory).

**Comment by raguay** [comment]
BTW: I ran the script 'expand' from the command line and it works fine. The issue is in the calling of the script from vimscript.

**Comment by didair** [comment]
If you try to copy expand.sh to your .vim directory, does that work?

**Comment by raguay** [comment]
Okay, I hardcoded the path to the expand.sh script and it ran it because it asked for permissions (on macOS mojave) and it still came out with the same issues. I also copied the line sent to the `system()` command and it runs on the command line.

**Comment by raguay** [comment]
Since hardcoding the command line doesn't work, moving the file will not either. I think my using SpaceVim is interacting with the commands/environment you are expecting to be there.

**Comment by didair** [comment]
Ahh thats too bad :/ Lets keep this one open and I can try to figure something out later..

**Comment by dustinknopoff** [comment]
I think this is actually an issue with the new permissions in Mojave. I tried making moving the entire script to be written in Python, but that would require a user to have a different from the System Python installed, and compiling vim with it's python3-interp set to that install.

**Comment by raguay** [comment]
That would be a bit too messy for a plugin.

**Comment by raguay** [comment]
I put this in a buffer:

```vimscript
echom system(sh '/Users/raguay/.cache/vimfiles/repos/github.com/dustinknopoff/TeaCode-Vim-Extension/plugin/../expand.sh' -e mint -t '   f init : Bool')
```

and executed the following command:

```vimscript
:%y"
:@"
```

The proper output from TeaCode was produced. Therefore, it's not an issue with permissions. It dies on the `js_decode` command for some reason. That should be a normal part of nvim, right?....I just added the `js_decode` to the test buffer and it says it's an unknown function.

BTW: The command line in the system call was developed from what the plugin creates except for I added the full path to the script command.

**Comment by raguay** [comment]
Okay, I changed `js_decode` to `json_decode` and hardcoded the path to the script. It now sort of works. I'm getting this error:

```
Error detected while processing function TeaCodeExpand:
line   22:
E735: Can only compare Dictionary with Dictionary
E15: Invalid expression: object ==? 'null'
line   43:
E117: Unknown function: provider#python#Call
line   46:
E121: Undefined variable: l
E15: Invalid expression: line + l + 1 " add offset
line   47:
E121: Undefined variable: c
E15: Invalid expression: cursor[2] + c - 1
line   48:
E121: Undefined variable: newline
E116: Invalid arguments for function setpos
```
But, the correct code is pasted into the buffer. But, the cursor isn't placed properly. Therefore, the errors aren't due to system permissions, but the code isn't portable to neovim.

**Comment by dustinknopoff** [comment]
Please pull/update to the latest version and the issue should be resolved.

**Comment by raguay** [comment]
Nope. `js_decode` doesn't work, but `json_decode` does. Then I still get the above errors. It's acting like the python statement doesn't work. Is it different in neovim than normal vim?

**Comment by dustinknopoff** [comment]
Can you post the output errors when using `json_decode`? After looking at the documentation, we should be using `json_decode`. `js_decode` does not permit keys being in quotes and output of `expand.sh` is. Not sure how it even worked previously. @didair

**Comment by raguay** [comment]
I did. The new output of errors is:

```
Error detected while processing function TeaCodeExpand:
line   22:
E735: Can only compare Dictionary with Dictionary
E15: Invalid expression: object ==? 'null'
line   43:
E117: Unknown function: provider#python#Call
line   46:
E121: Undefined variable: l
E15: Invalid expression: line + l + 1 " add offset
line   47:
E121: Undefined variable: c
E15: Invalid expression: cursor[2] + c - 1
line   48:
E121: Undefined variable: newline
E116: Invalid arguments for function setpos
```

This is after changing `js_decode` to `json_decode`. The first problem is comparing a dictionary to a non-dictionary. But, the big issue is the call to python is dying.

**Comment by dustinknopoff** [comment]
Please make sure your instance of the plugin is up to date. In #11, `object ==? 'null'` was changed to `s.result ==? null`. Will be pushing `js_decode()` => `json_decode()` soon.

**Comment by raguay** [comment]
Okay, I got your complete new version pulled over. It still could not find the file. I added the full path name in single quotes (I have spaces in directory names) and changed the `js_decode` to `json_decode`. The error output is:

```
Error detected while processing function TeaCodeExpand:
line   40:
E117: Unknown function: provider#python#Call
line   43:
E121: Undefined variable: l
E15: Invalid expression: line + l + 1 " add offset
line   44:
E121: Undefined variable: c
E15: Invalid expression: cursor[2] + c - 1
line   45:
E121: Undefined variable: newline
E116: Invalid arguments for function setpos
```
Which is just dying on the python code. I know I have some python code in plugins in SpaceVim, so I'm not sure why it's not liking it. I've never done python in vimscript before at all.

**Comment by dustinknopoff** [comment]
Unfortunately, @didair and I don't know how to loop through the characters in a string in vimscript. This is the purpose of using python.

can you try changing `python << EOF` to `python3 << EOF`

**Comment by dustinknopoff** [comment]
Perhaps try following [this](https://spacevim.org/faq/#how-to-enable-py-and-py3-in-neovim) from SpaceVim's FAQ.

**Comment by raguay** [comment]
Okay, I did the environment variable first and it didn't help. Then, I edited the plugin script file to use `python3`. It is now working. I also have the direct path to the `expand.sh` file. If I change it back to just the `../expand.sh`, it doesn't work. I tried using the `let s:path = expand('<sfile>:p:h')` to get the script's directory, but that just gave the directory of the currently opened file.

**Comment by raguay** [comment]
I just did it without the environment variable and it still works. BTW: I installed the `neovim` library for my installation of python3 last night trying to see if that helped. I couldn't tell anything last night, but it might have been necessary for the script change to work as well. Neovim uses the python3 library so that it doesn't have to compile python into the source (at least, that is my understanding - This is where I found that:  https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim). Not sure.

**Comment by dustinknopoff** [comment]
I won't have the time to try and fix this, this week. @didair or @raguay would you like to try?

Should be something along the lines of checking `has('python')` and `has('python3')` and making the `python << EOF` match.

**Comment by didair** [comment]
Sorry for being inactive on this, but couldn't that be resolved by making an alias in the .bashrc or .profile?

**Comment by dustinknopoff** [comment]
I don’t think so. It’s a question of which python version the user’s vim is compiled with. I don’t think aliasing can effect the code in a vim function.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dustinknopoff** [comment]
@didair Running into this issue but I think I resolved the issue with python.

<img width="650" alt="screen shot 2018-11-12 at 3 09 21 pm" src="https://user-images.githubusercontent.com/23691663/48372587-08f74480-e68d-11e8-9b8e-044e0c4f23c7.png">

**Comment by raguay** [comment]
I've given a pull request that allows it work for neovim on my macOS.

**Comment by raguay** [comment]
I just added another fix that makes it work in both neovim and MacVim on my system. It's in a pull request in the both_pythons branch. Hopefully it can be merged in soon.

**Comment by dustinknopoff** [comment]
Going to mark this issue as closed after #16.
